config/routes.rb
Rails.application.routes.draw do
  resources :reviews_and_ratings
  root 'users#index'
  get 'sessions/new'

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  
  resources :users
  
  

end

app/models/reviews_and_rating.rb
class ReviewsAndRating < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  before_save { self.email = email.downcase }
  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }

  # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/reviews_and_ratings_controller.rb
class ReviewsAndRatingsController < ApplicationController
  before_action :set_reviews_and_rating, only: [:show, :edit, :update, :destroy]

  # GET /reviews_and_ratings
  # GET /reviews_and_ratings.json
  def index
    @reviews_and_ratings = ReviewsAndRating.all
  end

  # GET /reviews_and_ratings/1
  # GET /reviews_and_ratings/1.json
  def show
  end

  # GET /reviews_and_ratings/new
  def new
    @reviews_and_rating = ReviewsAndRating.new
  end

  # GET /reviews_and_ratings/1/edit
  def edit
  end

  # POST /reviews_and_ratings
  # POST /reviews_and_ratings.json
  def create
    @reviews_and_rating = ReviewsAndRating.new(reviews_and_rating_params)

    respond_to do |format|
      if @reviews_and_rating.save
        format.html { redirect_to @reviews_and_rating, notice: 'Reviews and rating was successfully created.' }
        format.json { render :show, status: :created, location: @reviews_and_rating }
      else
        format.html { render :new }
        format.json { render json: @reviews_and_rating.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reviews_and_ratings/1
  # PATCH/PUT /reviews_and_ratings/1.json
  def update
    respond_to do |format|
      if @reviews_and_rating.update(reviews_and_rating_params)
        format.html { redirect_to @reviews_and_rating, notice: 'Reviews and rating was successfully updated.' }
        format.json { render :show, status: :ok, location: @reviews_and_rating }
      else
        format.html { render :edit }
        format.json { render json: @reviews_and_rating.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews_and_ratings/1
  # DELETE /reviews_and_ratings/1.json
  def destroy
    @reviews_and_rating.destroy
    respond_to do |format|
      format.html { redirect_to reviews_and_ratings_url, notice: 'Reviews and rating was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reviews_and_rating
      @reviews_and_rating = ReviewsAndRating.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def reviews_and_rating_params
      params.fetch(:reviews_and_rating, {})
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      #p "User login successful"
      redirect_to root_url, :notice => "Login Successful"
      #flash[:success] = 'Login Successful'
    else
      #p "User login failure"
      redirect_to login_path, :notice => "Oops!! Invalid Username/Password. Please try again"
    end
  end  

  def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to users_path, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to users_path, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :password)
    end
    

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reviews_and_ratings_helper.rb
module ReviewsAndRatingsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end

  # Returns the current logged-in user (if any).
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_user.nil?
  end
  
  # Logs out the current user.
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "sample app", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <% if logged_in? %>
          <li><%= link_to "Users", '#' %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", '#' %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: "delete" %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BearcatFoodSearch</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/reviews_and_ratings/_form.html.erb
<%= form_for(@reviews_and_rating) do |f| %>
  <% if @reviews_and_rating.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@reviews_and_rating.errors.count, "error") %> prohibited this reviews_and_rating from being saved:</h2>

      <ul>
      <% @reviews_and_rating.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit "Rate"%>
    <%= f.submit "Stars"%>
  </div>
<% end %>

app/views/reviews_and_ratings/edit.html.erb
<h1>Editing Reviews And Rating</h1>

<%= render 'form' %>

<%= link_to 'Show', @reviews_and_rating %> |
<%= link_to 'Back', reviews_and_ratings_path %>

app/views/reviews_and_ratings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Reviews And Ratings</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reviews_and_ratings.each do |reviews_and_rating| %>
      <tr>
        <td><%= link_to 'Rate', reviews_and_rating %></td>
        <td><%= link_to 'Stars', reviews_and_rating %></td>
        <td><%= link_to 'Show', reviews_and_rating %></td>
        <td><%= link_to 'Edit', edit_reviews_and_rating(reviews_and_rating) %></td>
        <td><%= link_to 'Destroy', reviews_and_rating, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
    <%= form_tag do %>

  <%= label_tag :reviews_and_rating, 'ReviewsAndRating: ' %><br>
  <%= text_field_tag :reviews_and_rating %><br>
  <% end %>
  </tbody>
</table>


<br>

<%= link_to 'New Reviews and rating', new_reviews_and_rating_path %>
<%= link_to 'Rate', reviews_and_ratings_path %>

app/views/reviews_and_ratings/new.html.erb
<h1>New Reviews And Rating</h1>

<%= render 'form' %>

<%= link_to 'Back', reviews_and_ratings_path %>

app/views/reviews_and_ratings/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_reviews_and_rating_path(@reviews_and_rating) %> |
<%= link_to 'Back', reviews_and_ratings_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name %>
      </br></br>
      <%= f.label :email %>
      <%= f.email_field :email %>
      </br></br>   
      <%= f.label :password %>
      <%= f.password_field :password %>
      </br></br>
      <%= f.submit "Submit", class: "btn btn-primary" %>
      </br></br>
    <% end %>
  </div>
</div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Bearcat Food Search</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Sign Up', new_user_path %>
<%= link_to 'Login', login_path %>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

app/views/users/signin.html.erb
<% provide(:title, "Sign in") %>
<h1>Sign in</h1>

<%= form_tag do %>

  <%= label_tag :user, 'Username: ' %><br>
  <%= text_field_tag :user %><br>

  <%= label_tag :password, 'Password: ' %><br>
  <%= password_field_tag :password %><br>
 -
  <%= submit_tag 'Submit' %>

<% end %>